### ISSUE TITLE
Domain is mixed up with event sourcing aspect, maybe it should be more isolated

### ISSUE THREAD

**Issue by anschnapp** [mat3e/3pigs-ddd#1]
I hope feeback (in form of an issue) is welcome in this project. Otherwise you could just close this issue ;)

I like the idea of this DDD and clean architecture example project :)

I was very curious about how you implement all the logical borders. And i was also curious if the domain will be really pure and isolated. (one of the major ideas of DDD)

IMHO the domain object are too much coupled with event sourcing logic.
AFAIK the domain layer should be as pure as possible in regards to the domain.
So, the logic and objects should only represents logic and models which belongs to the domain of the 3 pigs.
But in the original story of the 3 pigs and the bad wolf there are no terms or functions like snapshots or events.

So I would vote for putting this technical detail away from the domain, pretty much in the same way as the database layer was isolated here.

What do you think about it? Or do I get something wrong regarding the general architecture layout?

**Comment by mat3e** [comment]
Hello, feedback is always welcome :)

This codebase helps in my tech talk on DDD and Clean Architecture. Unfortunately, I've been presenting it just in Polish so far, so all the recordings (e.g. [the most recent one](https://www.youtube.com/watch?v=LVN7tof5LDg)) and [slides](https://mat3e.github.io/talks/3pigs/click.html) are not yet translated. In the talk I explain more on the presented ideas.

I treat snapshots as building blocks, next to the entities, domain services, factories and so on. As you can see, I even have a base contract/helper interfaces in [`ddd` subpackage](https://github.com/mat3e/3pigs-ddd/tree/master/shared/src/main/java/io/github/mat3e/ddd) and snapshots are under `vo`, so they are like value objects to me. I learnt this technique 3+ years ago on a DDD workshop and I found it very useful and pragmatic. 
* After the years of writing CRUDs it can be shocking and hard to start having entities without getters and setters 😄
  * I've even seen the aggregates with accessors (especially C# examples)
* Snapshots are like the middle-ground between pure DDD and the anemic model
* It helps me, e.g. storing the aggregates, mapping them, etc.
* I explain snapshots as an X-ray photo of the current domain object state
* Aggregates and entities can be X-rayed without any problems and work on the photos doesn't affect the original objects

The purest approach without snapshots which comes to my mind is to map directly from aggregates to DB. `domain` module should remain clean from mapping dependencies (even JPA annotations) and the whole mapping should still happen in `adapters`. Worth mentioning that currently, there is no JPA in the project. I use [Spring Data JDBC with Spring Data Repositories and Spring annotations](https://docs.spring.io/spring-data/jdbc/docs/2.0.3.RELEASE/reference/html/#jdbc.repositories). For the new approach I'd consider using a simple tool for mapping (like [JDBI](http://jdbi.org/)) or JPA with it's `orm.xml` mapping file.
I think I could create a new branch with such a version.

And when it comes to events, domain events have always been part of the DDD toolkit. The problem is some developers confuse domain and application events. Here it's rather OK, it's not like the domain is aware of an abstract concept of events, but it knows `HouseAbandoned` and `WolfResignedFromAttacking` may occur.
Worth noting my helpers contain `EventsDrivenRepository`, but it's not used. The example domain is not event-sourced. It's a simplified case - the aggregate and the domain service are just publishing the events. To be more precise - aggregate stores events to publish (and passes them with its snapshot) and the service just publishes with `DomainEventPublisher`.

For me it's OK that entities/aggregates store events while services publish them directly, but it could be changed to have the same approach in all domain parts. Example solutions:
1. Aggregate could take `DomainEventPublisher` as a method parameter and just use it when needed
2. Aggregate and service shouldn't publish events, but instead of having `void` commands, they should return `Set` of events or a generic "result" object including the events to publish

What do you think?

**Comment by anschnapp** [comment]
Thanks for all the information :)

I guess I have to watch your presentation when it's available on english. This X-ray photo analogy sounds really interesting.

My experience about combining DDD with event sourcing was within the Axon Framework.
I remembered it in a way that the model could be complete pure without any hint of the persistent at all.
But I just looked it up again and also there the domain was aware about events, in fact only events handlers was able to change the domain (so event sourcing was well supported).

So, never mind and thanks for the insights. 👍
